#pragma once

#define PETER_BFPTOUCH 0
#define PETER_INDUCTIVE 0
#define PETER_ROBSCAR 0
#define PETER_SERVOSWITCH 1

#define PETER_PROBE (PETER_BFPTOUCH || PETER_INDUCTIVE || PETER_ROBSCAR || PETER_SERVOSWITCH)

// sanity check
#if (PETER_BFPTOUCH + PETER_INDUCTIVE + PETER_ROBSCAR + PETER_SERVOSWITCH) > 1
#error "only 1 type of probe allowed"
#endif